cameras: {}
system:
  detected_display:
    actual_resolution: 1920x1080
    aspect_ratio: '16:9'
    color_depth: 24
    refresh_rate: 60
  performance:
    current_cpu_usage: 45.2
    gpu_acceleration: true
    last_optimization: '2025-06-23T10:15:30Z'
    memory_usage: 312
